"""Add team_content_bucket_association table

Revision ID: 3420b791a6a9
Revises: a1d5e7f77afd
Create Date: 2025-04-29 16:11:27.090266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3420b791a6a9'
down_revision: Union[str, None] = 'a1d5e7f77afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_content_bucket_association',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('content_bucket_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_bucket_id'], ['content_buckets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'content_bucket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_content_bucket_association')
    # ### end Alembic commands ###
