"""Create run artifacts table

Revision ID: 6cdffa015b80
Revises: a65dc41f3700
Create Date: 2025-04-28 20:20:11.396304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdffa015b80'
down_revision: Union[str, None] = 'a65dc41f3700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.Enum('FILE', 'IMAGE', 'TEXT', 'JSON', 'OTHER', name='artifacttype'), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('artifact_metadata', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_artifacts_name'), 'run_artifacts', ['name'], unique=False)
    op.create_index(op.f('ix_run_artifacts_run_id'), 'run_artifacts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_artifacts_run_id'), table_name='run_artifacts')
    op.drop_index(op.f('ix_run_artifacts_name'), table_name='run_artifacts')
    op.drop_table('run_artifacts')
    # ### end Alembic commands ###
