"""Create agent schedules table

Revision ID: 8632dc72f6c1
Revises: bd389c217b70
Create Date: 2025-04-28 20:15:42.987362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8632dc72f6c1'
down_revision: Union[str, None] = 'bd389c217b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cron_schedule', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('input_variables', sa.JSON(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_schedules_agent_id'), 'agent_schedules', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_schedules_agent_id'), table_name='agent_schedules')
    op.drop_table('agent_schedules')
    # ### end Alembic commands ###
