"""Create run logs table

Revision ID: a65dc41f3700
Revises: 6ef0542e654b
Create Date: 2025-04-28 20:18:56.323403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65dc41f3700'
down_revision: Union[str, None] = '6ef0542e654b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_logs_level'), 'run_logs', ['level'], unique=False)
    op.create_index(op.f('ix_run_logs_run_id'), 'run_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_logs_timestamp'), 'run_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_logs_timestamp'), table_name='run_logs')
    op.drop_index(op.f('ix_run_logs_run_id'), table_name='run_logs')
    op.drop_index(op.f('ix_run_logs_level'), table_name='run_logs')
    op.drop_table('run_logs')
    # ### end Alembic commands ###
